#!/bin/sh
#
# bootstrap

set -e

#
# Welcome to Play
#

echo ""
echo "  Staffr"
echo "  Employee Management for without the HR"
echo ""

#
# Check for Redis
#
if test ! $(which redis-server)
then
  echo "  x You need to install Redis. If you use Homebrew, you can run:"
  echo "    brew install redis"
  exit
else
  echo "  + Redis found."
fi

#
# Check for Bundler
#
if test ! $(which bundle)
then
  echo "  x You need to install Bundler:"
  echo "    gem install bundler"
  exit
else
  echo "  + Bundler found."
fi

#
# Install gems
#
echo "  + Bootstrapping your Rubies."
bundle install --binstubs --local --path vendor/gems --quiet

#
# Setup database
#

rake db:create && rake db:migrate
echo "  + Database setup"

#
# Startup instructions
#
echo ""

echo "  Good work. We're ready to rock."
echo "  Run 'rake start' to start playing."
