#!/bin/sh
#
# bootstrap

set -e

#
# Welcome to Staffr
#

echo ""
echo "  Staffr"
echo "  Employee Management for without the HR"
echo ""

#
# Check for Redis
#
# if test ! $(which redis-server)
# then
#   echo "  x You need to install Redis. If you use Homebrew, you can run:"
#   echo "    brew install redis"
#   exit
# else
#   echo "  + Redis found."
# fi

#
# Check for Bundler
#
if test ! $(which bundle)
then
  echo "  x You need to install Bundler:"
  echo "    gem install bundler"
  exit
else
  echo "  + Bundler found."
fi

#
# Install gems
#
echo "  + Bootstrapping your Rubies."
bundle check --path vendor/gems 2>&1 > /dev/null || {
  bundle install --path vendor/gems --quiet --without production
}

# Startup instructions
#
echo "  Good work. We're ready to go!"
